global:
  type: 'color'
  category: 'alerts'
imports:
  - ./color.yml
props:
  INFO:
    value: "#E8FAFC"
  CONFIRMATION:
    value: "#E5F7F1"
  ERROR:
    value: "#FFEBEE"
  WARNING:
    value: "#FFF6D8"