global:
  type: color
  category: colors
props: &COLORS
  WHITE:
    value: '#fff'
  BLACK:
    value: '#000'
  RED000:
    value: '#fdecf1'
  RED100:
    value: '#fbd6e3'
  RED200:
    value: '#f9bed2'    
  RED300:
    value: '#f6a2be'
  RED400:
    value: '#f37da5'
  RED500:
    value: '#ee467e'
  RED600:
    value: '#d73f71'
  RED700:
    value: '#bc3763'
  RED800:
    value: '#9b2d52'
  RED900:
    value: '#6f203b'
  YELLOW000:
    value: '#fef5e1'
  YELLOW100:
    value: '#feebc2'
  YELLOW200:
    value: '#fee0a0'
  YELLOW300:
    value: '#fdd479'
  YELLOW400:
    value: '#fdc64e'
  YELLOW500:
    value: '#fdb61c'
  YELLOW600:
    value: '#e4a419'
  YELLOW700:
    value: '#c99016'
  YELLOW800:
    value: '#a77812'
  YELLOW900:
    value: '#78560d'
  PURPLE000:
    value: '#f3effa'
  PURPLE100:
    value: '#e6def5'
  PURPLE200:
    value: '#d8cbf0'
  PURPLE300:
    value: '#c8b6e9'
  PURPLE400:
    value: '#b59ee2'
  PURPLE500:
    value: '#9f81da'
  PURPLE600:
    value: '#8f74c4'
  PURPLE700:
    value: '#7d65ac'
  PURPLE800:
    value: '#67548e'
  PURPLE900:
    value: '#493b65'
  GREEN000:
    value: '#e8f9f3'
  GREEN100:
    value: '#d0f3e7'
  GREEN200:
    value: '#b5ecd9'
  GREEN300:
    value: '#98e4ca'
  GREEN400:
    value: '#76dcb8'
  GREEN500:
    value: '#4ed2a4'
  GREEN600:
    value: '#46be94'
  GREEN700:
    value: '#3da682'
  GREEN800:
    value: '#338a6c'
  GREEN900:
    value: '#25644e'
  BLUE000:
    value: '#e8f6f8'
  BLUE100:
    value: '#d0ecf2'
  BLUE200:
    value: '#b5e2eb'
  BLUE300:
    value: '#97d6e3'
  BLUE400:
    value: '#75c8d9'
  BLUE500:
    value: '#4db9cf'
  BLUE600:
    value: '#45a7bb'
  BLUE700:
    value: '#3d92a4'
  BLUE800:
    value: '#327988'
  BLUE900:
    value: '#245761'
  NAVY000:
    value: '#EAEAEE'
  NAVY100:
    value: '#D5D5DC'
  NAVY200:
    value: '#C0C0CB'
  NAVY300:
    value: '#ABABB9'
  NAVY400:
    value: '#9697AB'
  NAVY500:
    value: '#808296'
  NAVY600:
    value: '#6B6D85'
  NAVY700:
    value: '#565873'
  NAVY800:
    value: '#414262'
  NAVY900:
    value: '#2C2E50'
  GREY000:
    value: '#F9FAFC'
  GREY100:
    value: '#EDF1F5'
  GREY200:
    value: '#dde1e4'
  GREY300:
    value: '#cdd3d8'
  GREY400:
    value: '#bdc4cb'
  GREY500:
    value: '#abb4bb'
  GREY600:
    value: '#98a0a7'
  GREY700:
    value: '#83898f'
  GREY800:
    value: '#676c71'
  GREY900:
    value: '#3c3f42'
  RED:
    value: '{!RED500}'
  BLUE:
    value: '{ BLUE500}'
  PURPLE:
    value: '{!PURPLE500}'
  YELLOW:
    value: '{!YELLOW500}'
  GREEN:
    value: '{!GREEN500}'
  NAVY:
    value: '{!NAVY900}'
  GREY:
    value: '{!GREY600}'
  CHARCOAL:
    value: '{!NAVY700}'
  SLATE:
    value: '{!NAVY600}'
  SILVER:
    value: '{!GREY500}'
  PLATINUM:
    value: '{!GREY300}'
  SNOW:
    value: '{!GREY200}'
  NONE:
    value: ''
    type: string
  INHERIT:
    value: 'inherit'
    type: unit
  CURRENT_COLOR:
    value: 'currentColor'
    type: unit
aliases: *COLORS
