global:
  type: border
  category: input
imports:
  - ./color.yml
props:
  INPUT_DEFAULT_BACKGROUND:
    type: color
    value: '{!WHITE}'
  INPUT_DEFAULT_BORDER:
    value: 1px solid {!GREY200}
  INPUT_DEFAULT_COLOR:
    type: color
    value: '{!NAVY900}'
  INPUT_HOVER_BORDER:
    value: 1px solid {!GREY500}
  INPUT_ACTIVE_BORDER:
    value: 1px solid {!GREY600}
  INPUT_DISABLED_BORDER:
    value: 1px solid {!GREY200}
  INPUT_DISABLED_BACKGROUND:
    type: color
    value: '{!GREY100}'
  INPUT_DISABLED_COLOR:
    type: color
    value: '{!GREY400}'
  INPUT_READONLY_BORDER:
    value: 1px dashed {!GREY200}
  INPUT_READONLY_BACKGROUND:
    type: color
    value: '{!GREY100}'
  INPUT_READONLY_COLOR:
    type: color
    value: '{!GREY400}'
  INPUT_PLACEHOLDER_COLOR:
    type: 'color'
    value: '{!GREY500}'
  INPUT_BORDER_RADIUS:
    type: 'border-radius'
    value: 4px
